(watch statistics)
(load program.clp)
(reset)
(open test.json test.json)
(assert (filename test.json))
(open test2.json test2.json)
(assert (filename test2.json))
(open test3.json test3.json)
(assert (filename test3.json))
(open test4.json test4.json)
(assert (filename test4.json))
(open test5.json test5.json)
(assert (filename test5.json))
(run)
